using Microsoft.CodeAnalysis;
using System.Collections.Immutable;

namespace Soenneker.Quark.Gen.SimpleIcons;

[Generator]
public sealed class SimpleIconsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("Generated.g.cs", "// Generated by Soenneker.Quark.Gen.SimpleIcons" + System.Environment.NewLine);
        });
    }
}
